### ISSUE TITLE
Contents of the WWIIDK.xml

### ISSUE THREAD

**Issue by panther2** [DerKuenstler/WWIIDK#10]
Note: Not all of them will be necessary.
- [x] xml-version
- [x] doctype
- [x] game-info
- [x] game-loader
- [x] game-trA minimum Version
- [x] map-territory definitions
- [x] map-territory connections
- [x] resourceList
- [x] playerList
- [ ] unitList
- [ ] relationshipTypes
- [ ] gamePlay-delegate
- [ ] gamePlay-sequences
- [ ] production-productionRule
- [ ] production-repairRule
- [ ] productionFrontier
- [ ] playerProduction
- [ ] playerRepair
- [ ] technologies
- [ ] playerTech
- [ ] attachmentList-relationshipTypeAttachment
- [ ] attachmentList-techAttachment
- [ ] attachmentList-unitAttachment
- [ ] attachmentList-canalAttachment
- [ ] attachmentList-territoryEffectAttachment
- [ ] attachmentList-supportAttachment"Unit"
- [ ] objectiveAttachment"Nation"
- [ ] conditionAttachment"Nation"
- [ ] triggerAttachment"Nation"
- [ ] rulesAttachment
- [ ] playerAttachment
- [ ] politicalActionAttachment
- [ ] userActionAttachment
- [ ] techAbilityAttachment
- [ ] ownerInitialize-territoryOwener
- [ ] unitInitialize-unitPlacement
- [ ] resourceInitialize
- [ ] relationshipInitialize
- [ ] propertyList (game options)
- [ ] propertyList-notes

It will be difficult to figure out what is necessary for the special purpose of this map and what is the minimum for the map to work in the game.

**Comment by DerKuenstler** [comment]
Looks great!

**Comment by panther2** [comment]
This issue will be reopened if the project is going to be continued.
