### ISSUE TITLE
Include DK's local files into the Repository

### ISSUE THREAD

**Issue by panther2** [DerKuenstler/WWIIDK#11]
I will show you how to securely add
- [x] capitols.txt 
- [x] files into the flags folder.

and possible other files ready to be merged to the repo.
Please add what is ready to the above list.

**Comment by DerKuenstler** [comment]
reliefTiles folder
territoryNames folder
name_place.txt

**Comment by panther2** [comment]
We will do the capitals only for now.
I will give you a "walkthrough" here, soon.

**Comment by panther2** [comment]
Here we go:
When you go to the repsitory 
https://github.com/DerKuenstler/WWIIDK
you will notice on the left side the box "Branch-Master".

The master branch is the main branch, where all productive files go. It is the basis for the final release.
This branch is very sensitive because if any errors were introduced there, it would cause erroneous downloads/releases.

So to keep this master branch save, changes are introduced by different branches (working-branch).
These branches are "short-time" copies of the master, created to perform a change. After the change has been merged to the master, the branch should be deleted.

Now, this is how to create a branch and apply changes:
1. Go to your repository and click on "Branch: master"
2. Insert a name for your new branch, for example DK_capitals
3. Click on the blue field "Create branch: DK_capitals from 'master'
4. Your branch has been created. You now see Branch: DK_capitals at the (grey) place where Branch: master had been before
5. Now you can apply the changes to the DK_capitals_branch. The master branch won't be affected by this.
6. For a start now add the capitols.txt to the DK_capitals_branch. First, click on 'map'. You will see that the files and folders appear, and the branch is still DK_capitals. Right to Branch: DK-capitals you see WWIIDK/maps. Seeing this you know that the file capitols.txt will be included here.
7. Click "Upload files" to be found right above.
8. Click Choose Files and add the capitols.txt that you created.
9. You see the file being uploaded then.
10. In the Commit changes field enter a Headline such as "Upload capitols.txt". You might add a desription to the field below (but there is not much to say here).
11. Keep 'Commit directly to the DK_capitals branch' marked and hit "Commit changes"
12. Now we need to push this change to the master branch. We will do this by a so called "pull request". Now find the line that contains the green "Compare and pull request button". This will compare your "new" DK_capitals branch with the master branch, identify the changes and open a pull request. Click the button "Compare and pull request button".
13. You are now in the 'Open a pull request' window. You see that master is compared with DK_capitals and that the change is ready to be merged. You can change the headline and the comments (or leave them as they are in this case). On the bottom of the page you see the changes that will be merged. It is the file capitols.txt with it's content. Click on the green "create pull request" button.
14. In the next window you will see that the pull request has been created. And that it is ready to be merged. Don't do anything here. As this is the point where I will check if everything is ok to be merged. When I have reviewed the changes I will merge them. If you go back to the repository's main page now, you will notice that there is a "1" next to "Pull requests" in the upper line, indicating that there is a pull request to be worked at.

When I have merged the branch DK_capitals should be deleted. Your pull request will change it's status from 'open' to 'closed', then. 

To prevent from mixing up subjects, files and issues, it is recommended to create a working branch for every subject to change. So you won't include for example changes to the game.xml to the same working branch or pull request as adding "reliefTiles".

Concerning the flags, we will include a bulk of graphic files alltogether of course - but this is the next step.

So try this out, please. I will check, merge and be back to you then.

**Comment by DerKuenstler** [comment]
Will work on doing this...

**Comment by panther2** [comment]
Congrats, you did it. I have checked and merged the pull request #17  and you can now see the file capitols.txt in the master branch of the repository. When having merged I have been asked to delete the DK_capitals branch, so I did that.

Now do the same uploading the flag symbols to the folder "flags". 
Create a new "working branch", you can call it DK_flags for example.
In the new working branch first klick on "map", then on "flags".
Choose the six relevant flags-png and upload them all together.
So apart from going one directory deeper the process is exactly the same as before.

**Comment by panther2** [comment]
Well done, the only small change I made was to rename the title of the pull request to "Add large_nations.png files (Capital Marker)" - it will be easier to find it, in case we need to review it an any time.
