### ISSUE TITLE
Standard and non-standard units ... 

### ISSUE THREAD

**Issue by panther2** [DerKuenstler/WWIIDK#13]
... that have to be included:

**Standard:**
- [ ] Infantry
- [ ] Mechanized Infantry
- [ ] Artillery
- [ ] Tanks
- [ ] Industrial Complex
- [ ] Anti Aircraft Gun
- [ ] Fighter
- [ ] Tactical Bomber
- [ ] Strategic Bomber
- [ ] Battleship
- [ ] Aircraft Carrier
- [ ] Cruiser
- [ ] Transport
- [ ] Submarine
- [ ] Destroyer

**Non-standard:**
- [ ] Air Borne Infantry
- [ ] Coastal Guns 
- [ ] Blockhouses
- [ ] Sub Pens
- [ ] Entrenchment Chips
- [ ] Transport Planes 
- [ ] Flagships

@DerKuenstler 
Is this list complete?
Are all of these units subject to buy in the Arms Buildup Phases?

**Comment by DerKuenstler** [comment]
Yes that's everything. Everything can be bought during arms buildup (entrenchment is free). I have already made all the graphics for the 7 Non-standard units.

**Comment by panther2** [comment]
Great!
Regarding the non-standard units we need to investigate whether there are similar units in other maps. We can use your graphics then but for coding the xml I hope there is as much similarity to unit attachments already present as possible,

**Comment by panther2** [comment]
This issue will be reopened if the project is going to be continued.
