### ISSUE TITLE
Contents of the repository

### ISSUE THREAD

**Issue by panther2** [DerKuenstler/WWIIDK#14]
This is a list of the files/folders possibly included into the project
Not all of them migt be needed..
A marked checkbox indicates, that the respective content has already been included.

Files in Root directory ("map"):
- [x] capitols.txt
- [x] centers.txt
- [x] map.properties
- [x] name_place.txt
- [x] place.txt
- [x] polygons.txt
- [x] pu_Place.txt
- [x] decorations.txt
- [x] smallMap.jpg
- [x] reliefTile.png (this need not be part of the Repo, we keep it local)
- [x] WWIIDK.png

Folders:
- [x] baseTiles
- [x] flags
- [x] games
- [x] misc
- [x] PUs
- [x] reliefTiles
- [x] territoryNames
- [x] units

Files in Folders:
- [x] baseTiles -> all the tiles.png
- [x] flags -> large capital markers (anything else?)
- [x] games -> game.xml (to be developped)
- [x] misc -> more decorations files
- [x] PUs -> PU_images.png
- [x] reliefTiles -> all the relief_tiles.png
- [x] territoryNames -> all the territory/seazone_names.png
- [x] units -> all the units.png

The last thing we will add ist the reliefTile.png and the tiles, because we will be able to decide about the appropriate transparency of this layer when the complete map is ready (and working) and visible.

**Comment by DerKuenstler** [comment]
OK looks good...

**Comment by panther2** [comment]
#32 is merged, and this issue is closed for now
