### ISSUE TITLE
Working on Territory (and Sea Zone) Names

### ISSUE THREAD

**Issue by panther2** [DerKuenstler/WWIIDK#16]
Though you correctly used the tool to create the name_place.txt there is some work necessary:

The names of the png-files have to exactly correspond to the territory (seazone) names (using underscores instead of blanks).

For example: 

For the territory "Eastern United States" the filename must be Eastern_United_States.png
For the (impassable) Pripyat Marshes the filename must be Pripyat_Marshes.png
For the seazone "14 Sea Zone" the filename must be 14_Sea_Zone.jpg
and so on...

For a quick reference, here is a list of what we have defined so far:
[TTandSZList.txt](https://github.com/DerKuenstler/WWIIDK/files/510454/TTandSZList.txt)

**Comment by DerKuenstler** [comment]
OK will work on correcting...

**Comment by DerKuenstler** [comment]
I'm kind of lost here. I am looking at my current name_place.txt file after adding sea zone numbers, straits, canals, and convoy raiding zones last night. Sea zones there are named like "59", and not "59_sea_zone". yet I only copied these names from a working map,  "world_war_ii_global-master" - I don't understand how they work with those names on that map. I tried changing two of the names and when I loaded name_place.txt found I had to place them all over again with the new names.  There are also names that run together like "FrenchMadagascar" and names that contain the word and a description of where it goes like "Impassable-Himalayas" but only "impassable" appears on the map. This png and name were also just copies from the global master map. It would be hours of work to change all this - just want to make sure I do it right.

**Comment by panther2** [comment]
world_war_ii_global does not to use name_place.txt, but places everything in decorations.txt. This appears to be a different approach. If you look at WW_II_v6_1941 (for TripleA Version 1.9) you will see what I was talking about above.

Can you please describe step by step how you proceeded after hitting "Decoration placer"?
There are some options and I need to know what you had chosen.

I will investigate then and we will discuss how to go on here...

**Comment by DerKuenstler** [comment]
OK I pick map WWIIDK
centers txt file "yes"
polygons.txt file "yes"
select name_place from list of type of image points
I keep hitting enter (default choice) until I get to the map. (the tutorial said "if you don't know what you are doing, just keep hitting enter)

I looked at WW_II_v6_1941 and see what you are saying - I can change all the names like that I you want.

**Comment by panther2** [comment]
I'll take a look as soon as I have some time today, thanks.

**Comment by panther2** [comment]
OK, now I have looked into it.

At first please edit the filenames so that they exactly match the territory names according to the list that I provided above.

Instead of blanks please use underscores such as 
59_Sea_Zone.png
French_Indo-China.png

After that:
- Please create an empty name_place.txt in the map folder (where the other .txt-files are)
- Run the Decoration Placer
- Select WWIIDK.png
- Confirm use of centers.txt
- Confirm use of polygons.txt
- Confirm explaining text with ok
- Select name_place
- Hit "Folder full of Images"
- Select the new name_place.txt
- Select Point is Bottom Left
- Select Points do not end in .png

Alternatively we could set the Territory Names as Decoration using the given file names, but that would mess things up too much, I think. So changing the file names seems to be worth it. You can do it either manually or use a software for this, such as AntRenamer (http://www.antp.be/software/renamer). 
Good luck!

**Comment by DerKuenstler** [comment]
OK will try it...

**Comment by DerKuenstler** [comment]
I made a new territoryNames and name_place.txt file in the format needed but forgot how to upload it here - guess I will email them to you...

**Comment by panther2** [comment]
Thank you. Please see #20 to read again how creating a pull request (upload/merge) works.

As you sent me the files by mail, I will check them and merge them later.
Thank you!

**Comment by panther2** [comment]
So I took a look into the files. Good job on renaming the file names accordingly! Must have been some work.

I have some questions, though:

**a) Folder territoryNames**
There are now territories (or names) included, that were not pre-defined before. For example Pro_Allies_Anti_USSSR_Afghanistan.png or
Suez_Canal.png
66_Sea_Zone.png (up to 71_Sea_Zone).

These have no equivalent to the territory definitions we created before  - so how did they come into it?

There are also Convoy zone symbols, Kamikaze Symbols and Flag symbols included ... these images should not be in the folder territoryNames but be part of other decoration folders instead, I suppose - did you include them here on purpose?

I do not know how this might affect the result.

**b) File name_place.txt**

Here are definitons of spots not being part of our defined territories, too. This is related to the images-subject above of course. So I assume you added those "non-pre-defined" parts when doing the territory names, too? There are no such territories in centers.txt or polygons.txt. So how were you able to do this? Have you entered those manually in any way? I'm just confused...

Looks like we have a mix of territoryNames and other decorations now...

There is another issue, caused by the change from TripleA 1.8 to 1.9:
The territory names in the name_place.txt now include the underscores of the file names. So the map maker tool does not convert that back when creating the txt-files. We have to test this with the map whether this might cause issues, I think I have to inform the developpers in case it does.

For now, please just tell me about what you did regarding those "extra" information stated under a) and b). We will decide later on how to go on. Thank you :-)

**Comment by DerKuenstler** [comment]
Well I really don't know what I'm doing but - I just "created" pngs for every visual thing I wanted to be on the map (except territory ipc values) and put them in the territoryNames folder. Then I ran the Decoration Placer as you instructed. There were some names already in place on the map. (I assume the file names that didn't need changing) All of the pngs that I created and changed the file name for were piled up together in the upper right corner. I just moved them all one by one to where they should go and saved it. I did not change any other files.

**Comment by DerKuenstler** [comment]
I put these extra things in territoryNames because I noticed they were in other existing map territoryNames folders. for example, the world_war_ii_v6_1941-master territoryNames folder has all the seazone names in it also. I put names of canals and kamikaze zones here since I reasoned they will not need coding. We will not actually be playing the game on the map. (there is no need of the AI understanding Kamikaze, convoy raid  and canal rules - it is just necessary to visually see where they are for placing units) If this is all wrong I can change it.

**Comment by panther2** [comment]
Thanks for explaining.
Actually a seazone is a territory for the purpose of the name_place.txt. So this is why v6 includes territory names and sea zone names (but only these). I am afraid this is the way it has to be done here, too. Because concerning territoryNames there appears to be an interdependency to the game.xml, where the territory/seazone names are defined. But there will be no decoration defined in the xml. For example 'Suez Canal' is a decoration that will never appear in the xml.

But your work was not in vain:
Please keep only the territory and seazone names (only those needed) inside the territoryNames folder. Place all the other png files in another folder, called "misc". After that use the decoration placer again to create the name_place.txt as you did before, but only with the pre-defined territory and seazone names. After that please use the decoration placer again but choose "**decorations.txt will place any kind of image you want anywhere, using the 'misc' folder**" this time ( #21 ).
But don't place the territories' PU values there... this will be another task... (those images go to the "PUs" folder).

Thank you :-)

**Comment by panther2** [comment]
Thanks. I am closing this and open other issues for the non-related things to do.
