### ISSUE TITLE
Creating a working xml

### ISSUE THREAD

**Issue by panther2** [DerKuenstler/WWIIDK#19]
Referencing to #6 and #10 I have thought about how to have a working game.xml ready as soon as possible (not meaning that this will be a quick and easy job).

So this is what I will do next:
I have already started with the game.xml. I will continue adding in everything what appears to be necessary to just open the map to see how it looks.
For this I will edit in all needed territory and nation-related information and only very few unit information (for example only Infantry just for a start).
Having the XML of a minimalistic map ("Minimap" or anything else) as a sample, I will then edit in a minimal amount of mechanics to open our game.xml without errors (hopefully).

When this has been successfully done, I will try to edit in the special requirements for WWIIDK.

Seems to be a long road, though...

**Comment by DerKuenstler** [comment]
There is no hurry - if it stops being fun we can put it aside for a while.

**Comment by panther2** [comment]
This issue will be reopened if the project is going to be continued.
