### ISSUE TITLE
map.properties needs decisions and fixes

### ISSUE THREAD

**Issue by panther2** [DerKuenstler/WWIIDK#2]
- [x] think about image size (map size)
- [x] correct impassible -> impassable (for 1.9)
- [x] are colors ok?
- [x] map.showCapitolMarkers=true
- [x] map.showTerritoryNames=true
- [x] map.showSeaZoneNames=true
- [x] map.drawNamesFromTopLeft=false
- [x] map.useNation_convoyFlags=false
- [x] map.hasRelief=true
- [x] map.showResources=true (PUs on territory)

@DerKuenstler (parts of) this has to be correctly configured depending on your wishes concerning the "look of the map". Please see #3

**Comment by DerKuenstler** [comment]
What map size setting do you recommend?
The colors you speak of are OK. They should match AA classic colors. (except for Italy & China which were not in classic) Germany=grey, UK=tan, Italy=celery, Russia=brown, Japan=yellow, USA=dark green, China=dark red.

**Comment by panther2** [comment]
I can't say what I recommend in fact, the map size you have chosen for your image is similar to the present v3-map, but smaller than the WWII_Global-map.

If everything looks fine the size should be ok. If there are overlappings or problems to place decoration and units accurately, the map size should be increased (probably like Global). In this case, we need to redo the Map Creator process, too.

**Comment by DerKuenstler** [comment]
OK I'd say leave it for now unless the size causes problems later.

**Comment by DerKuenstler** [comment]
If I fix something (like the impassable spelling) on my map on my local PC what should I do with the fix? Just keep it there and notify you that it is fixed?

**Comment by panther2** [comment]
Great that you have tried that out, but 1.8 works with the misspelling. So please leave it "wrong" as long as you deal with the 1.8 map-maker.
The correction is necessary for the final 1.9 map as many spelling issues have been corrected there. 
I need to adjust the map.properties at a later point and -while there- will correct the spelling.

**Comment by DerKuenstler** [comment]
OK

**Comment by panther2** [comment]
Fix and some adjustments done with #12

**Comment by panther2** [comment]
Sample is the map.properties from v6

**Comment by panther2** [comment]
#31 should be enough for the moment
Maybe further adjustment is needed once we have a working map.
I am closing this for now.

**Comment by DerKuenstler** [comment]
OK
