### ISSUE TITLE
Adding PUs-images (to PUs folder) and pu_place.txt

### ISSUE THREAD

**Issue by panther2** [DerKuenstler/WWIIDK#24]
As in v6-map.

This works similar to creating the capitals.txt.

Using the decorations placer again, please choose pu_place.txt  
There is only one image needed as example to define all the points in the territories.
So choose any image from the PUs folder.
There is interdependency to the xml.

**Comment by panther2** [comment]
Merged #25 . Thank you.

**Comment by DerKuenstler** [comment]
Glad it worked!
