### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by DerKuenstler** [DerKuenstler/WWIIDK#26]
I'm working on the units folder. Do I have to make all of the units for the China folder that I put in the other folders, even though they can't be used? (China can only use infantry, artillery, one fighter, and entrenchment)

**Comment by panther2** [comment]
I am not sure.
Though in the xml only the units used are defined per nation, it appears that in other maps the full set is placed even in China's folder.
I would say only the used units should be enough for now. If we encounter problems, we can add anything else later, anyway. 

Referencing #13

**Comment by DerKuenstler** [comment]
OK will do
