### ISSUE TITLE
Some data needed

### ISSUE THREAD

**Issue by panther2** [DerKuenstler/WWIIDK#29]
Please see your mails and go to the spreadsheet that I have prepared.
You would do me a great favor if you filled in the required data.

When coding the xml it would be very hard to access the several files for searching the required information. So having all at one glance would be a lot easier.

Thanks a lot.

**Comment by DerKuenstler** [comment]
I'm filling it in but how do I save it? I don't see a save button anywhere.

**Comment by DerKuenstler** [comment]
Never mind -I see it auto saves...

**Comment by panther2** [comment]
Thank you!
