### ISSUE TITLE
Graphics to do

### ISSUE THREAD

**Issue by panther2** [DerKuenstler/WWIIDK#3]
- [x] Add a relief
- [x] Add territory name (decoration)
- [x] Add sea zone number (decoration)
- [x] Add ipc value (decoration) -> file pu_place.txt and folder "PUs"
- [x] Add convoy raiding decoration
- [x] Add units

@DerKuenstler 
Please see again these two links:
http://tripleamaps.sourceforge.net/old/doc/map_and_map_skin_making_overview.html
http://tripleadev.1671093.n2.nabble.com/How-to-make-new-map-graphic-from-scratch-td7593642.html

What do you actually want to be visible on the map - and how should this be performed
a) the engine can show some information in a very simple way using the coded data
b) you can add decoration instead to make information more attractive?

Depending on your needs, this has to be coded (quick and easy), see #2 , and the graphics have to be added.

Take a look at the maps you have downloaded. You can easily see, which items have been included to the map according to a) and b).

**Comment by DerKuenstler** [comment]
The map should show the territory names, ipc values, and be tinted their country's color. The three special convoy raiding areas in the Atlantic should be marked. Sea zone numbers should show up. That should be all.

**Comment by panther2** [comment]
Good - I have adjusted the above list accordingly.
Do you want it as decoration (such as in Global) or
do you want it generated from the map data (such as in Pact Of Steel)?

Do you intend to work on a (new) relief?

**Comment by DerKuenstler** [comment]
If the relief is where the country colors are tinted and texture added for land and sea, I would like to do that, yes. Since this map won't actually be played on, the territories won't ever need to change color with ownership.

**Comment by panther2** [comment]
The country colors are tinted by TripleA according to the colors that you defined when creating the map.properties file. The textures for land and sea are added by the relief, indeed. Some people draw out the original borders more significantly in the relief (as they are only 1 point black in the base map).

**Comment by DerKuenstler** [comment]
OK so I only need the relief to stay white with grey textures then...ocean areas with lighter blue wave textures...

**Comment by panther2** [comment]
Sounds good!

**Comment by DerKuenstler** [comment]
I further refined territory names and name_place files - will keep them on my PC unless you say otherwise...

**Comment by panther2** [comment]
Great - I will open an issue to introduce you to the process of adding this securely to the repository - in a way that it can be checked by me before it is merged. 

But I am short on time today, so we will deal with it tomorrow.

**Comment by DerKuenstler** [comment]
OK

**Comment by panther2** [comment]
> I further refined territory names and name_place files 

Does this include Sea Zone names, too?

**Comment by DerKuenstler** [comment]
No didn't do sea zones yet...should that all be in the same txt file?

**Comment by panther2** [comment]
Yes, consider sea zones as territories for this purpose.

**Comment by DerKuenstler** [comment]
OK will do...

**Comment by DerKuenstler** [comment]
I made the units folders and sent them by email because I couldn't figure out how to load them on here...

**Comment by panther2** [comment]
OK , thanks, I'll take a look soon.

Yes, I have not created the units folders before. This is a bit tricky (in fact it is easy but you have to know how) - because you cannot add empty folders. 

In short: GitHub does not store empty folders. But GitHub allows you to create files using your browser when working at your repository. When you give that file a name you may enter a directory name for placing that file, too. This the file as well as the folder are created. So this is why I always create folders using a "dummy" file. I delete that dummy file after the real files are placed there.

**Comment by DerKuenstler** [comment]
OK

**Comment by panther2** [comment]
Nice, looks good! 

I have created the nations subfolders. See #28 

You can now add all the images into their respective subfolders.
Please create a new branch for doing this, as I deleted the old branch to avoid errors.

**Comment by DerKuenstler** [comment]
OK

**Comment by DerKuenstler** [comment]
Added unit images in new branch and deleted dummy files...

**Comment by panther2** [comment]
Very good. I am closing this for now. We will reopen this issue, if needed.
