### ISSUE TITLE
Chinese units

### ISSUE THREAD

**Issue by panther2** [DerKuenstler/WWIIDK#4]
@DerKuenstler 
Do you want/need Chinese units on the board?
I understand that China is played by the US-Player. Chinese units are not part of the arms buildup phase, correct?

**Comment by DerKuenstler** [comment]
Yes the Chinese don't participate in the arms buildup - they should appear on the map already, before the arms buildup starts. their setup is found at the end of the section on China in the 7.0 rules PDF. In addition, one free AA gun and one free Factory are put on each nations' capital before the arms buildup begins. These are the only units that should start out on the map already.
