### ISSUE TITLE
Saving capitols.txt?

### ISSUE THREAD

**Issue by DerKuenstler** [DerKuenstler/WWIIDK#5]
OK I'm trying to get familiar with things here - I've placed out my capitals using decorations placement, but when I go to "save image locations" it makes a text file called capitols in my folder but the text file is empty. There is no text in there so when I close this window all my placements are lost. 

![save](https://cloud.githubusercontent.com/assets/22566243/19026398/0e443ddc-88eb-11e6-81b6-ae70b93a1e7b.jpg)

**Comment by panther2** [comment]
Just to be sure:

Did you do it using the 1.9-map creator (that has issues), now you have TripleA 1.9 installed?

We need to use the 1.8-map creator.

I will check it, in case you used 1.8.

**Comment by DerKuenstler** [comment]
Yes I'm using 1.8- I'm starting to suspect that my version of java is not right - perhaps send me a link to to exactly what you use?

**Comment by panther2** [comment]
Please read

https://java.com/en/download/faq/remove_olderversions.xml 

before, and then install this (assuming your Windows is 64bit)

http://javadl.oracle.com/webapps/download/AutoDL?BundleId=211999

The site
https://java.com/en/download/manual.jsp
is always a good source for downloading the latest Java.

Nevertheless, I will try to place a capital myself, later.

**Comment by panther2** [comment]
Ok, I successfully placed a capital, showing up in the capitols.txt.
Please try again.

Also please see https://github.com/DerKuenstler/WWIIDK/issues/3#issuecomment-251089308 in this context.

**Comment by DerKuenstler** [comment]
OK will do above...

**Comment by DerKuenstler** [comment]
I'm still having trouble with this. I ran the Java remove program and installed the current java. What happens is it will save the first capital I put down. Then "save current and keep them on map and load new file." Then I put the new capitol down, then save, and it erases the other capitols in the txt file and keeps only the last one I put down. they still show up in the graphics screen but aren't there in the text file. See, I placed USA last here and saved, but only USA shows up in the text file now...
![cap2](https://cloud.githubusercontent.com/assets/22566243/19056950/2c6c0798-8992-11e6-85cf-41c1b07e4b2f.jpg)

**Comment by panther2** [comment]
I will take a look...

**Comment by panther2** [comment]
I see what happened. The map creator's documentation sometimes is misleading, indeed.
The concept here is, that inside the capitols.txt only the coordinates for the Capital-Images are saved.
The look of the image here is irrelevant - it will be determined by the images in the flags subfolder of our map and the definitions in the game.xml.

So this will work:
1. Create an empty file capitols.txt (not mandatory but perhaps easier) - where the other txt-files are
2. In TripleA run the Decoration Placer
3. Select the WWIIDK.png
4. Accept the centers.txt File Suggestion
5. Accept the polygons.txt File Suggestion
6. Click OK to the explaining message
7. Choose capitols 
8. Click Text File Full of Points
9. Select capitols.txt
10. Select Point is Bottom Left
11. Select Let Me Select Territories
12. Select the predefined Neutral_large.png
13. Read next messsage and hit ok
14. Move the mouse to the first territory, say Eastern USA
15. Decide where you want the bottom-left point where the image should be placed and right-click to place
16. Move the mouse to the next territory, decide where you want the bottom-left point and right-click to place
17. place the other capitals accordingly
18. When finished goto File - Save Image Location
19. Confirm capitols.txt

ready!

Before finishing the map (deco placer) looks similar like this:

![capitols](https://cloud.githubusercontent.com/assets/20812775/19073671/82c269a2-8a3c-11e6-8121-6f7085c07cd9.jpg)

And the capitols.txt is filled like this:

![capitalstxt](https://cloud.githubusercontent.com/assets/20812775/19073680/95b20f5e-8a3c-11e6-9c3c-77e1232eee9d.jpg)

Please copy the Capitol-marker-flags into the map/flags subfolder.
You will find pre-created images in the TripleA-directory, that is
C:\Games\TripleA1809\assets\flags
on my system and similar on yours, depending on where you installed it.

Our map's flags-folder should look similar to this, then:

![flags](https://cloud.githubusercontent.com/assets/20812775/19073692/a5adf026-8a3c-11e6-88b4-073f6d825567.jpg)

Please try and report back.

**Comment by DerKuenstler** [comment]
Ah....very helpful - thanks - will try this! Do I add "medium" size flags to all the territories that have ownership the same way then?  Does the xml change the flag in the game as the territory ownership changes?

**Comment by panther2** [comment]
No, you don't. Territory ownership is indicated by the nation's color only - and if ownership changes, the nation's underlying color changes for that territory. This is done by the game engine, that "learns" from the xml how the game is set up and "manages" the game going through all phases.

**Comment by DerKuenstler** [comment]
Oh OK - what is the purpose of the "medium" and "small" flags in the folder then?

**Comment by DerKuenstler** [comment]
OK I fixed this like you said - thanks!

**Comment by panther2** [comment]
> Oh OK - what is the purpose of the "medium" and "small" flags in the folder then?

Maybe there are other routines where they are needed, we will see...

Also you could use them as decoration, of course. For example on the OOB-gameboards you see a roundel of the original controller on every territory - (though this is not needed as the Original Owner will be coded in the XML and shown in the Territory panel.)
