### ISSUE TITLE
Possible sea zone issue

### ISSUE THREAD

**Issue by panther2** [DerKuenstler/WWIIDK#7]
Sea Zones have been created as "sea zone 15" instead of "15 Sea Zone" to be found in existing maps. Not sure if this could cause problems.

In case of problems either the map creator has to be run again or the created map files have to be manually edited. 
- [x] centers.txt
- [x] polygons.txt
- [x] place.txt
- [x] game.xml

**Comment by DerKuenstler** [comment]
OK

**Comment by panther2** [comment]
I needed to fix this, as I noticed issues. Please redownload the latest zip for continuing locally.
As long as you did not create any decoration in seazones, this issue can be closed.

**Comment by DerKuenstler** [comment]
OK
